// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7mAx75MTbe8G5tgByIauKzTWTSDiiWI',
    appId: '1:241557995838:web:5aa1bb039c3bfb27266c6f',
    messagingSenderId: '241557995838',
    projectId: 'exemplo-sl-5ee98',
    authDomain: 'exemplo-sl-5ee98.firebaseapp.com',
    storageBucket: 'exemplo-sl-5ee98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyt3IAJ9qa_Ma2BYw2LY506tzScOu7mM',
    appId: '1:241557995838:android:d90374d2c82091df266c6f',
    messagingSenderId: '241557995838',
    projectId: 'exemplo-sl-5ee98',
    storageBucket: 'exemplo-sl-5ee98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18K-ThYTz45QPvNlj8nzSkZq3n5yNayA',
    appId: '1:241557995838:ios:c2ebde1ac5ebdbd9266c6f',
    messagingSenderId: '241557995838',
    projectId: 'exemplo-sl-5ee98',
    storageBucket: 'exemplo-sl-5ee98.appspot.com',
    iosClientId: '241557995838-nm4tusamt5up36fvtmqpi6r2et736f96.apps.googleusercontent.com',
    iosBundleId: 'com.example.httpSampleFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18K-ThYTz45QPvNlj8nzSkZq3n5yNayA',
    appId: '1:241557995838:ios:17066b2602ecf3d0266c6f',
    messagingSenderId: '241557995838',
    projectId: 'exemplo-sl-5ee98',
    storageBucket: 'exemplo-sl-5ee98.appspot.com',
    iosClientId: '241557995838-br905654o9ilfd3i9i5tdbqoviif7803.apps.googleusercontent.com',
    iosBundleId: 'com.example.httpSampleFire.RunnerTests',
  );
}
